--
-- Файл сгенерирован с помощью SQLiteStudio v3.1.1 в Вс ноя 10 18:20:44 2019
--
-- Использованная кодировка текста: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: log
DROP TABLE IF EXISTS log;
CREATE TABLE log (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER REFERENCES user (id) ON DELETE CASCADE ON UPDATE NO ACTION MATCH SIMPLE, event VARCHAR (1000), event_date DATETIME);

-- Таблица: server
DROP TABLE IF EXISTS server;
CREATE TABLE server (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR (100) NOT NULL, uri VARCHAR (100) NOT NULL, version_date DATETIME NOT NULL, deleted BOOLEAN NOT NULL DEFAULT false);

-- Таблица: server_user
DROP TABLE IF EXISTS server_user;
CREATE TABLE server_user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL REFERENCES user (id) ON DELETE NO ACTION ON UPDATE NO ACTION MATCH SIMPLE, server_id INTEGER REFERENCES server (id) ON DELETE NO ACTION ON UPDATE NO ACTION MATCH SIMPLE NOT NULL, version_date DATETIME NOT NULL, deleted BOOLEAN NOT NULL DEFAULT false);

-- Таблица: user
DROP TABLE IF EXISTS user;
CREATE TABLE user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR (100) NOT NULL, login VARCHAR (100) NOT NULL, password VARCHAR (100) NOT NULL, version_date DATETIME NOT NULL, deleted BOOLEAN NOT NULL DEFAULT false);

-- Таблица: version
DROP TABLE IF EXISTS version;
CREATE TABLE version (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, version VARCHAR (100) NOT NULL, version_date DATETIME NOT NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
